=begin
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
=end

def triangle_numbers(n) #n=num divisors
  i = 0
  while true
    t_num = i * (i + 1) / 2

    if divisors(t_num) > n
      return t_num
    end
    i += 1
  end
end

def divisors(n)
  cnt = 0

  i = 1
  while i * i <= n
    if n % i == 0
      cnt += 1
    end
    i += 1
  end
  cnt * 2
end

puts triangle_numbers(500)
