#Each new term in the Fibonacci sequence is generated by adding the previous two terms.
#By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
def find_fib(max)
  fib = [1,2]
  while fib[-1] <= max
    fib << fib[-1] + fib[-2]
  end

  fib.select { |num| num.even? }.reduce(:+)
end

puts find_fib(4000000)
